/* BRINKY FIESTA SUITE · recovery-first v2.4.0 */
(()=>{'use strict';
const DB='brinky_recovery_first_v240',STORE='state',KEY='snapshot';
const KEYS=['brinky_contracts_only_v1','brinky_contracts_v1','brinky_quotes_v1','brinky_folio_state_v1','brinky_loyalty_v2','brinky_loyalty_v1','brinky_loyalty_settings_v2','brinky_loyalty_settings_v1','brinky_loyalty_folio_v2','brinky_expenses_v1','brinky_whatsapp_messages_v1','brinky_club_message_templates_v2','brinky_deleted_items_v222','brinky_cloud_backup_config_v1','brinky_cloud_backup_session_v1','brinky_cloud_sync_meta_v222','brinky_club_cloud_pending_v2','brinky_contracts_capture_preferences_v1'];
const ARRAY_KEYS=new Set(['brinky_contracts_only_v1','brinky_contracts_v1','brinky_quotes_v1','brinky_loyalty_v2','brinky_loyalty_v1','brinky_expenses_v1']);
const parse=(raw,fb)=>{try{return JSON.parse(raw)}catch{return fb}};
const meaningful=()=>['brinky_contracts_only_v1','brinky_quotes_v1','brinky_loyalty_v2','brinky_expenses_v1'].some(k=>{const v=parse(localStorage.getItem(k),'[]');return Array.isArray(v)&&v.length});
function mergeArray(a,b){a=Array.isArray(a)?a:[];b=Array.isArray(b)?b:[];const out=[...a],idx=new Map(),id=x=>String(x?.id||x?.code||x?.phone||'');out.forEach((x,i)=>{const k=id(x);if(k)idx.set(k,i)});for(const r of b){const k=id(r);if(!k){out.push(r);continue}const i=idx.get(k);if(i===undefined){idx.set(k,out.length);out.push(r)}else{const rt=Date.parse(r?.updatedAt||r?.createdAt||'')||0,lt=Date.parse(out[i]?.updatedAt||out[i]?.createdAt||'')||0;if(rt>lt)out[i]=r}}return out}
function restoreKeys(keys){let changed=false;for(const k of KEYS){if(keys?.[k]==null)continue;const local=localStorage.getItem(k);if(ARRAY_KEYS.has(k)){const raw=JSON.stringify(mergeArray(parse(local,'[]'),parse(keys[k],'[]')));if(raw!==local){localStorage.setItem(k,raw);changed=true}}else if(local==null){localStorage.setItem(k,keys[k]);changed=true}}if(!localStorage.getItem('brinky_contracts_only_v1')&&localStorage.getItem('brinky_contracts_v1'))localStorage.setItem('brinky_contracts_only_v1',localStorage.getItem('brinky_contracts_v1'));if(!localStorage.getItem('brinky_loyalty_v2')&&localStorage.getItem('brinky_loyalty_v1'))localStorage.setItem('brinky_loyalty_v2',localStorage.getItem('brinky_loyalty_v1'));if(!localStorage.getItem('brinky_loyalty_settings_v2')&&localStorage.getItem('brinky_loyalty_settings_v1'))localStorage.setItem('brinky_loyalty_settings_v2',localStorage.getItem('brinky_loyalty_settings_v1'));return changed}
async function open(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE);};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function readOwn(){try{const db=await open();return await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>{db.close();res(r.result||null)};r.onerror=()=>{db.close();rej(r.error)}})}catch{return null}}
async function writeOwn(){try{const db=await open(),keys={};for(const k of KEYS){const v=localStorage.getItem(k);if(v!=null)keys[k]=v}if(!Object.keys(keys).length){db.close();return}await new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put({savedAt:new Date().toISOString(),keys},KEY);t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close()}catch{}}
async function scanOtherIndexedDb(){try{if(!indexedDB.databases)return null;const dbs=await indexedDB.databases();for(const info of dbs||[]){if(!info?.name||info.name===DB)continue;let d;try{d=await new Promise((res,rej)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}catch{continue}for(const store of [...d.objectStoreNames]){if(!['snapshots','state','backup'].includes(store))continue;try{const v=await new Promise((res,rej)=>{const tx=d.transaction(store,'readonly'),r=tx.objectStore(store).get('latest');r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});if(v?.keys){d.close();restoreKeys(v.keys);return v}}catch{}}d.close()}}catch{}return null}
async function scanBackupFolder(){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('brinky_fiesta_suite_file_handles_v1');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(!db.objectStoreNames.contains('handles')){db.close();return false}const h=await new Promise((res,rej)=>{const tx=db.transaction('handles','readonly'),r=tx.objectStore('handles').get('backupRoot');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();if(!h)return false;if(h.queryPermission&&(await h.queryPermission({mode:'read'}))!=='granted')return false;const fh=await h.getFileHandle('BRINKY_FIESTA_SUITE_RESPALDO_COMPLETO.json').catch(()=>null);if(!fh)return false;const snap=parse(await (await fh.getFile()).text(),null);if(!snap)return false;const keys={};if(Array.isArray(snap.contracts))keys['brinky_contracts_only_v1']=JSON.stringify(snap.contracts);if(Array.isArray(snap.quotes))keys['brinky_quotes_v1']=JSON.stringify(snap.quotes);if(snap.folioState)keys['brinky_folio_state_v1']=JSON.stringify(snap.folioState);if(Array.isArray(snap.members))keys['brinky_loyalty_v2']=JSON.stringify(snap.members);if(snap.loyaltySettings)keys['brinky_loyalty_settings_v2']=JSON.stringify(snap.loyaltySettings);if(snap.loyaltyFolio!=null)keys['brinky_loyalty_folio_v2']=String(snap.loyaltyFolio);if(Array.isArray(snap.expenses))keys['brinky_expenses_v1']=JSON.stringify(snap.expenses);if(snap.whatsappMessages)keys['brinky_whatsapp_messages_v1']=JSON.stringify(snap.whatsappMessages);if(snap.clubTemplates)keys['brinky_club_message_templates_v2']=JSON.stringify(snap.clubTemplates);if(snap.deletedItems)keys['brinky_deleted_items_v222']=JSON.stringify(snap.deletedItems);if(snap.cloudConfig?.url&&snap.cloudConfig?.anonKey)keys['brinky_cloud_backup_config_v1']=JSON.stringify(snap.cloudConfig);restoreKeys(keys);return true}catch{return false}}
async function boot(){const own=await readOwn();if(own?.keys)restoreKeys(own.keys);if(!meaningful())await scanOtherIndexedDb();if(!meaningful())await scanBackupFolder();await writeOwn();window.__brinkyRecoveryReady=true;window.dispatchEvent(new CustomEvent('brinky-recovery-ready'))}
window.addEventListener('pagehide',writeOwn);window.addEventListener('beforeunload',writeOwn);boot();
})();